### ISSUE TITLE
#F02 Footer html content

### ISSUE THREAD

**Issue by JimLynx** [Code-Institute-Community/ci-hackathon-app#56] opened 2020-10-15 13:47 UTC
@JimLynx
Adding initial content and layout for footer so that it can be styled accordingly.
Links can be adapted to whatever content (Privacy Policy, FAQ etc) is included in the footer later

**Comment by TravelTimN** [comment] 2020-10-15 14:26
@JimLynx  is this a duplicate of #53 ?

**Comment by JimLynx** [comment] 2020-10-15 14:58
ok so html content and styling are 2 separate or one combined pull?

**Comment by TravelTimN** [comment] 2020-10-15 15:43
@JimLynx they're essentially the same thing you're working on, just HTML and CSS, would technically be two commits if you want, but I suppose if you want to split that into two PRs 🤔 Could add the HTML, un-styled, request the PR to go through, then after sorted, work on the CSS as a second PR. I don't think we need two separate "issues" though.

**Comment by TravelTimN** [comment] 2020-10-15 15:57
@JimLynx I'll go ahead and close this "Issue" here, and if you could go ahead and continue working on #53 . Thanks!

**Closed by TravelTimN** 2020-10-15 15:57 UTC
